### ISSUE TITLE
not able to load the pre-trained weight file

### ISSUE THREAD

**Issue by trilokpadhi** [weizheliu/People-Flows#1]
hi 
Thanks for the nice repo but when i test here is an issue that comes up .

`Traceback (most recent call last):
  File "test.py", line 37, in <module>
    checkpoint = torch.load('fdst.pth.tar')
  File "/home/trilok/.local/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/trilok/.local/lib/python3.6/site-packages/torch/serialization.py", line 555, in _load
    return legacy_load(f)
  File "/home/trilok/.local/lib/python3.6/site-packages/torch/serialization.py", line 469, in legacy_load
    tar.extract('storages', path=tmpdir)
  File "/usr/lib/python3.6/tarfile.py", line 2043, in extract
    tarinfo = self.getmember(member)
  File "/usr/lib/python3.6/tarfile.py", line 1754, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'storages' not found"
`

**Comment by weizheliu** [comment]
Based on the error, it seems that you do not use the absolute path for the weight file, please try to replace 'fdst.pth.tar' with '/PATH/TO/fdst.pth.tar', then it should work.

**Comment by weizheliu** [comment]
I close this issue for now, if the above solution does not work for you, feel free to let me know and re-open it.
