### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by Trevo1** [weizheliu/People-Flows#7]
Traceback (most recent call last):
  File "train.py", line 254, in <module>
    main()
  File "train.py", line 58, in main
    train(train_list, model, criterion, optimizer, epoch)
  File "train.py", line 166, in train
    loss.backward()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\autograd\__init__.py", line 156, in backward
   allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag

when I run train.py,I have met this problem.

**Comment by weizheliu** [comment]
Could you try it with pytorch 1.3.1 and see if it solve the problem?

**Comment by Trevo1** [comment]
thanks for your reply， and I think I've solved this problem, but then I ran into another problem, so I gave up on the project...

In Pytorch, tensor needs to be defined as the type of require_grad to obtain the gradient.
You can add "requires_grad=True" when defining variables
